---
version: 1.0.3
slug: porcupine3
name: Porcupine 3
description: Porcupine 3 using the Wyoming protocol
url: https://github.com/piitaya/rhasspy-hassio-addons/tree/master/porcupine3
arch:
  - amd64
  - aarch64
  - armv7
init: false
discovery:
  - wyoming
options:
  sensitivity: 0.5
  debug_logging: false
  access_key: ""
schema:
  sensitivity: float
  debug_logging: bool
  access_key: str
ports:
  "10400/tcp": null
homeassistant: 2023.9.0
